steps:
- name: sonarsource/sonar-scanner-cli
  args:
    - '-Dsonar.host.url=http://104.197.249.40:9000'
    - '-Dsonar.login=sqp_4f7ac6f9c3c8b18ea2219839a639b8c5bec786c0'
    - '-Dsonar.projectKey=ea-k8s-app'
    - '-Dsonar.projectName=ea-k8s-app'
    - '-Dsonar.qualitygate.wait=true'
    - '-Dsonar.sources=.'
- name: bash
  script: |
    #!/usr/bin/env bash
    apk add --update docker openrc yq
    rc-update add docker boot
    docker build -t gcr.io/ea-k8s/ea-k8s-app:$HOSTNAME .
    docker push gcr.io/ea-k8s/ea-k8s-app:$HOSTNAME
    yq -i '.spec.template.spec.containers[0].image= "gcr.io/ea-k8s/ea-k8s-app:'$HOSTNAME'"' deployment.yaml
