apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ea-k8s-cd
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/erdenayates/ea-k8s-repo
    targetRevision: HEAD
    path: argocd 
  destination: 
    server: https://kubernetes.default.svc
    namespace: appp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
